### ISSUE TITLE
new.target not supported by Safari, IE, and Edge

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/ASN1.js#19]
It seems we use new.target, according to: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target

It is not supported by Safari, Edge, IE: 
![image](https://cloud.githubusercontent.com/assets/1619279/21863357/faf6a4f8-d7f1-11e6-8eb6-b4ba019c377c.png)

We are experiencing an error currently errors in workers as well as with UglifyJS on on IE, as is expected as a result.

I would have assumed the transpile would have moved to:
```
this.constructor.name === "ClassName"
```
For this but it seemed not to.

This bug is to track this issue.

**Comment by YuryStrozhevsky** [comment]
Seems there is no elegant way how to replace the "new.target". Thus I decided to just remove it - in fact the "new.target" needs only for additional "smart protection" from making abstract class and nothing else. So, it could be removed without any "side effects".

Solved in latest release.
