### ISSUE TITLE
Link to NPM is incorrect in Readme

### ISSUE THREAD

**Issue by ashergarland** [PeculiarVentures/ASN1.js#22]
Link to npm page is: https://www.npmjs.com/package/ASN1js
It should be changed to: https://www.npmjs.com/package/asn1js

Also, the link on the npm page to the github page is: github.com/PeculiarVenturess/ASN1.js
It should be changed to: github.com/PeculiarVenturess/asn1.js

The links are broken in both direction and makes it very difficult to find the correct pages to use asn1js as well as confusing search-engine-optimization.

**Comment by ashergarland** [comment]
https://github.com/PeculiarVentures/ASN1.js/pull/23

**Comment by rmhrisk** [comment]
@ashergarland I merged your PR, it addresses the first issue.

The second issue should be fixed with https://github.com/PeculiarVentures/ASN1.js/commit/7d67d5d34c2988ea545eeff136a605a5cf4faa1c

And the next version update @YuryStrozhevsky does.
