### ISSUE TITLE
Building for browser instruction

### ISSUE THREAD

**Issue by herrjemand** [PeculiarVentures/ASN1.js#24]
Is there any instructions on how to build it for browsers?

**Comment by rmhrisk** [comment]
To build it:

```
git clone git@github.com:PeculiarVentures/ASN1.js.git
npm i
npm run build
```

This will produce a cross-platform build, will work in node and the browser.

**Comment by herrjemand** [comment]
@rmhrisk That produces Node version, that is not compatible with browsers

**Comment by rmhrisk** [comment]
@herrjemand and what makes you say that?

**Comment by herrjemand** [comment]
@rmhrisk the fact that I've build it, and tested it.

**Comment by herrjemand** [comment]
@rmhrisk https://gist.github.com/herrjemand/38c39589f5eeb40b65b8002db629e322

**Comment by YuryStrozhevsky** [comment]
@herrjemand OK, then was it working for you or you still have a problems?

**Comment by herrjemand** [comment]
@rmhrisk @YuryStrozhevsky it was never working for me. It uses export everywhere.

**Comment by rmhrisk** [comment]
@herrjemand export is a es6 feature; see - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

It sounds like your asking how to transpile to ES5?

**Comment by herrjemand** [comment]
Jup. I feel like that needs to be part of build scripts.

**Comment by rmhrisk** [comment]
So to be clear, ES6 is well supported in modern browsers - http://caniuse.com/#search=es6

That said it is a fair feature request to show how to do ES5 in this project.

@YuryStrozhevsky is better suited to do that and we can as we have time. In the meantime this is a nice introduction to babel : https://www.jonathan-petitcolas.com/2015/03/09/transpiling-es6-to-es5-using-babel.html

You can also see examples of its use in the PKIjs repository.

**Comment by YuryStrozhevsky** [comment]
@herrjemand In version 2 of our packages (ASN1.js and PKI.js) we moved to a special way of working with JS code - "NPM is everywhere". You could check these links:
[http://dontkry.com/posts/code/using-npm-on-the-client-side.html](http://dontkry.com/posts/code/using-npm-on-the-client-side.html)
[http://beletsky.net/2015/04/npm-for-everything.html](http://beletsky.net/2015/04/npm-for-everything.html)
[http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging)

So, we do not provide a direct way how to use ASN1.js inside browser front-end applications. Instead you could use a way we were using inside [PKI.js examples](https://github.com/PeculiarVentures/PKI.js/tree/master/examples). If it would not be good for you the sorry, you could use ASN1.js v1 or just move to other implementations of ASN.1 parsers.

**Comment by herrjemand** [comment]
@rmhrisk 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

> Note: This feature is not implemented in any browsers natively at this time. It is implemented in many transpilers, such as the Traceur Compiler, Babel or Rollup.

**Comment by herrjemand** [comment]
@YuryStrozhevsky Maybe then we need add build script that does ES5 transpiling

**Comment by herrjemand** [comment]
@YuryStrozhevsky or remove mention of "It works in browsers". Another issue is that PKI.js build actually works in browser.

**Comment by YuryStrozhevsky** [comment]
@herrjemand In fact ES6 code works in almost all browsers, btw. And in fact "npm run build" command will build ES5 code for ASN1.js. The only issue I can see is that the ES5 code is using NPM code style and that is all. But it could be easily fixed - as you said PKI.js examples work in browser.

**Comment by YuryStrozhevsky** [comment]
@herrjemand BTW please note that inside PKI.js we are using more or less "exotic" way of working with packages - all packages are pure ES6 code, with all these "import/export". Then if we need to have a browser app we firstly using Rollup to making one huge bundle with ES6 code. And then if we need to have a ES5 code we use Babel on this huge bundle.
