### ISSUE TITLE
Object's schema was not verified against input data for CERT

### ISSUE THREAD

**Issue by ashergarland** [PeculiarVentures/ASN1.js#25]
Sometimes when converting a X.509 certificate from its raw base64 encoding to a PKI.js Certificate object I get the error "Object's schema was not verified against input data for CERT". These have been verified to be valid certificates - what does this error mean and would could it mean in terms of these certificates? Is it possible they are missing some sort expected value?

**Comment by rmhrisk** [comment]
Without the sample certificates we can not debug this.

**Comment by YuryStrozhevsky** [comment]
@ashergarland Most probably this is a problem in encoding of your BASE-64 data. Check [this issue](https://github.com/PeculiarVentures/PKI.js/issues/92), and [this issue](https://github.com/PeculiarVentures/PKI.js/issues/58), and [this issue](https://github.com/PeculiarVentures/ASN1.js/issues/16). So, we had many of such issues, but all were about incorrect encoding of the input data. Please verify all the data on your side.
