### ISSUE TITLE
Library don`t understand GeneralizedTime for example 2.5.29.16(Private key usage period)  in x.509

### ISSUE THREAD

**Issue by max2loboda** [PeculiarVentures/ASN1.js#28]
Library don`t understand GeneralizedTime for example 2.5.29.16(Private key usage period)  in x.509

**Comment by YuryStrozhevsky** [comment]
@max2loboda Please provide any BASE-64 encoded data which you think ASN1.js could not recognize.

**Comment by max2loboda** [comment]
-----BEGIN CERTIFICATE----- MIIGgDCCBiigAwIBAgIULSSnyTDit7QEAAAAjBgAAD85AAAwDQYLKoYkAgEBAQEDAQEwgegxJDAiBgNVBAoMG9CU0LXRgNC20ZbQvdGE0L7RgNC8J9GO0YHRgjFUMFIGA1UECwxL0JDQutGA0LXQtNC40YLQvtCy0LDQvdC40Lkg0YbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyMS8wLQYDVQQDDCbQkNCm0KHQmiDQlNC10YDQttGW0L3RhNC+0YDQvCfRjtGB0YLRgzEZMBcGA1UEBQwQVUEtMjUyODc5ODgtMjAxNTELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyMB4XDTE1MDkzMDA3MTgxOVoXDTE3MDkzMDA3MTgxOVowggE0MTAwLgYDVQQKDCfQotC10YHRgtC+0LLQsCDQvtGA0LPQsNC90ZbQt9Cw0YbRltGPIDIxLjAsBgNVBAsMJdCi0LXRgdGC0L7QstC40Lkg0L/RltC00YDQvtC30LTRltC7IDIxIzAhBgNVBAwMGtCi0LXRgdGC0YPQstCw0LvRjNC90LjQuiAyMTgwNgYDVQQDDC/QotC10YHRgtGD0LLQsNC70YzQvdC40LogMiBTRVRBTSDRjtGA0L7RgdC+0LHQsDEjMCEGA1UEBAwa0KLQtdGB0YLRg9Cy0LDQu9GM0L3QuNC6IDIxHTAbBgNVBCoMFFNFVEFNINGO0YDQvtGB0L7QsdCwMQ0wCwYDVQQFDAQ2Mjg0MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LIwgfIwgckGCyqGJAIBAQEBAwEBMIG5MHUwBwICAQECAQwCAQAEIRC+49tq6p4fhleMRcEllP+UI5Sn1zj5GH5lFQFylPTOAQIhAIAAAAAAAAAAAAAAAAAAAABnWSE68YLph9PhdxSQfUcNBCG2D9LY3OipNCPGEBvKkcR6AH5sMAsmzVVsmw59IO8pKgAEQKnW60XxPHCCgMSWeyMfXq32WOukwDcpHTjZa/Alyk4X+OlyDcYVtDool18Lwd6jZDi1ZOosF5/QEj5tuPrFeQQDJAAEITFlw2tY+QXxoM7PpC1muyOxE2vidfhKNGyjEoKkbQnJAaOCAsIwggK+MCkGA1UdDgQiBCDmGjvhcWbcZV38881epS0crovTx8n4GvqxyDbZEDcS4jArBgNVHSMEJDAigCCtJKfJMOK3tDdnvEyyyvmY6etRgbAM0Am8g1GItvp8CDAvBgNVHRAEKDAmoBEYDzIwMTUwOTMwMDcxODE5WqERGA8yMDE3MDkzMDA3MTgxOVowDgYDVR0PAQH/BAQDAgbAMBkGA1UdIAEB/wQPMA0wCwYJKoYkAgEBAQICMAwGA1UdEwEB/wQCMAAwNwYIKwYBBQUHAQMBAf8EKDAmMAsGCSqGJAIBAQECATAXBgYEAI5GAQIwDRMDVUFIAgMPQkACAQAwGwYDVR0RBBQwEoEQdGVzdDRAZXhlbXBsLmNvbTBLBgNVHR8ERDBCMECgPqA8hjpodHRwOi8vY2EuaW5mb3JtanVzdC51YS9kb3dubG9hZC9jcmxzL0NBLUFEMjRBN0M5LUZ1bGwuY3JsMEwGA1UdLgRFMEMwQaA/oD2GO2h0dHA6Ly9jYS5pbmZvcm1qdXN0LnVhL2Rvd25sb2FkL2NybHMvQ0EtQUQyNEE3QzktRGVsdGEuY3JsMIGABggrBgEFBQcBAQR0MHIwMgYIKwYBBQUHMAGGJmh0dHA6Ly9jYS5pbmZvcm1qdXN0LnVhL3NlcnZpY2VzL29jc3AvMDwGCCsGAQUFBzAChjBodHRwOi8vY2EuaW5mb3JtanVzdC51YS9jYS1jZXJ0aWZpY2F0ZXMvYWNzay5wN2IwQQYIKwYBBQUHAQsENTAzMDEGCCsGAQUFBzADhiVodHRwOi8vY2EuaW5mb3JtanVzdC51YS9zZXJ2aWNlcy90c3AvMEMGA1UdCQQ8MDowGgYMKoYkAgEBAQsBBAIBMQoTCDg3NjU0MzIxMBwGDCqGJAIBAQELAQQBATEMEwowOTcxMjM0NTY3MA0GCyqGJAIBAQEBAwEBA0MABEAiUYQBZKNy1W7mOONIGIirl7gdX+mB/cAzYSF9xt/sGS1suC/qZtxB3m70XOm2PKDwZ8f+ArlxGfbPKrHLXrFG -----END CERTIFICATE-----

**Comment by YuryStrozhevsky** [comment]
@max2loboda The problem in this certificate is not in ASN1.js but in incorrectly encoded "PrivateKeyUsagePeriod" extension. Just a simple example: here is what Windows shows on your certificate:
![untitled](https://user-images.githubusercontent.com/6128446/26915483-da1bb65e-4c2e-11e7-8b24-ec20a128c247.jpg)

And here is what Windows shows on correctly encoded certificate with "PrivateKeyUsagePeriod" extension:
![untitled_2](https://user-images.githubusercontent.com/6128446/26915499-efdb3bb8-4c2e-11e7-87bc-b73cbbe6ea7d.jpg)

So, ASN1.js can handle any ASN.1 data, including GeneralizedTime. But PKI.js would not parse your buggy certificate: you would see error in console "Error: Object's schema was not verified against input data for PrivateKeyUsagePeriod". Thus correct your certificate and the all would be fine.

**Comment by max2loboda** [comment]
Yes I agree. Thank you. Perhaps it makes sense to make the mode ignore errors in PKI.js. There are many certificates with such a mistake.

**Comment by YuryStrozhevsky** [comment]
@max2loboda Currently PKI.js works in a style "all or nothing". So, in a real certificates such ugly mistakes should not be allowed. But I would think on how to provide ability for parsing most of certificate's values for such buggy cases.

**Comment by max2loboda** [comment]
I do not find any certificate that Windows shows correctly "PrivateKeyUsagePeriod".

**Comment by YuryStrozhevsky** [comment]
Wow :) Then you need to report these issues to CA issuers.

**Comment by rmhrisk** [comment]
PrivateKeyUsagePeriod is a deprecated extension. You very likely won't find any WebPKI CA using it as a result.
