### ISSUE TITLE
'Utf8String' and other constructors missing from CommonJS module

### ISSUE THREAD

**Issue by mikemaccana** [PeculiarVentures/ASN1.js#30]
Utf8String and PrintableString and similar constructors seems missing from pkijs when imported as a commonjs module. 

Even searching recursively fails to find the constructors:

    > var asn1js = require('asn1js')
    > var findKey = require('find-key')
    > findKey(asn1js, 'Utf8String')
    []

I have some code using pkijs 1 that I'm attempting to port to pkijs 2, and recall the code was organized a little differently from normal commonJS modules. From the pkijs docs:

    // From 'How to use PKIjs with Node.js' on https://www.npmjs.com/package/pkijs
    var extend = require("node.extend");
    var common = require("asn1js/org/pkijs/common");
    var _asn1js = require("asn1js");
    var _pkijs = require("pkijs");
    var _ = require('lodash');
    var _x509schema = require("pkijs/org/pkijs/x509_schema");
    var asn1js = extend(true, _asn1js, common);
    var x509schema = extend(true, _x509schema, asn1js);
    var pkijs_1 = extend(true, _pkijs, asn1js);
    var pkijs = extend(true, pkijs_1, x509schema);

Is there something similar required for pkijs 2?

Using pkijs@2.0.59. How can I get the constructors from the CommonJS module? Thanks!

**Comment by YuryStrozhevsky** [comment]
@mikemaccana I made this simple test code:
```javascript
var asn1js = require("asn1js");
var utf8 = new asn1js.Utf8String();
console.log(typeof utf8);
console.log(utf8.valueBlock.value);
```

All works perfect.

**Comment by mikemaccana** [comment]
Thanks @YuryStrozhevsky, I got distracted by a couple of other things but I've moved to v2 now.
