### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by rudhras** [PeculiarVentures/ASN1.js#32]
Hello 
asn1 js file fails in IE11. is it coz of es6 version used and IE not yet support? in that case can you please let me know if there is a way out? 

Thanks
Rudhra

**Comment by rmhrisk** [comment]
IE11 does not support ES6 so you have to transpile it to ES5. Look at using Babel and the ES2015-preset - https://stackoverflow.com/questions/34747693/how-do-i-get-babel-6-to-compile-to-es5-javascript

**Comment by rudhras** [comment]
Thanks. It worked.

**Comment by Soulafein** [comment]
Looks like ASN1.js library is not ES5 compatible anymore and i can't use it as third-party library if i need IE11 support. Correct?

**Comment by YuryStrozhevsky** [comment]
You can use build dir. There you can find ES5 compiled code for ASN1js.

**Comment by Soulafein** [comment]
Yes i looked to compiled file and found lots of class definitions like `class LocalBaseBlock`, `class LocalIdentificationBlock`, arrow functions and some other ES6 things which are not ES5 and IE11 compatible.

**Comment by YuryStrozhevsky** [comment]
If you want a real ES5 code you need to change `package.json`:
```
 "engines": {
    "node": ">=4.0.0"
  },
```
And then re-build ASN1js code.

**Comment by Soulafein** [comment]
Ok, thanks
