### ISSUE TITLE
Node.js buffer constructor runtime deprecation

### ISSUE THREAD

**Issue by benjamingr** [PeculiarVentures/ASN1.js#36]
Hey, this repo was tagged in https://github.com/nodejs/node/issues/19079#issuecomment-374536006 but I don't see any `new Buffer` usage here.  

Just making sure this is tracked and Node communicates clearly that `new Buffer` is runtime-deprecated in v10. If you need any help with the new buffer usage in the code please let us know!

**Comment by ChALkeR** [comment]
```
8384865	asn1.js-4.10.1.tgz/lib/asn1/base/buffer.js:93:    out = new Buffer(this.length);
8384865	asn1.js-4.10.1.tgz/lib/asn1/decoders/pem.js:47:  var input = new Buffer(base64, 'base64');
8384865	asn1.js-4.10.1.tgz/lib/asn1/encoders/der.js:131:  var objid = new Buffer(size);
8384865	asn1.js-4.10.1.tgz/lib/asn1/encoders/der.js:202:    num = new Buffer(numArray);
8384865	asn1.js-4.10.1.tgz/lib/asn1/encoders/der.js:210:    var out = new Buffer(size);
8384865	asn1.js-4.10.1.tgz/lib/asn1/encoders/der.js:236:  return this._createEncoderBuffer(new Buffer(out));
8384865	asn1.js-4.10.1.tgz/lib/asn1/encoders/der.js:40:    var header = new Buffer(2);
8384865	asn1.js-4.10.1.tgz/lib/asn1/encoders/der.js:52:  var header = new Buffer(1 + 1 + lenOctets);
8384865	asn1.js-4.10.1.tgz/lib/asn1/encoders/der.js:66:    var buf = new Buffer(str.length * 2);
```

**Comment by YuryStrozhevsky** [comment]
@benjamingr @ChALkeR Guys, you missed that my package has another name. And has no "lib/asn1/<blah-blah>" files. You listed problems from other package, probably from [this one](https://github.com/lapo-luchini/asn1js). My package from the very beginning using ONLY ArrayBuffer type and nothing else. No dependencies from Node.js Buffer type at all.

**Comment by ChALkeR** [comment]
@benjamingr Entries in my package list are npm package names, so the correct package for this is https://www.npmjs.com/package/asn1.js.

**Comment by benjamingr** [comment]
@ChALkeR yes, this was just a mistype on my end - I opened an issue in the correct repo already :)
