### ISSUE TITLE
fromBER() can't decode DER-encoded certificate

### ISSUE THREAD

**Issue by gnarea** [PeculiarVentures/ASN1.js#39]
Hello,

I'm not sure if I'm doing something wrong or I've found a bug, but I can't get this library to parse a DER-encoded X.509 certificate with the following code:

```js
const asn1js = require('asn1js');
const fs = require('fs');

const certDer = fs.readFileSync('certificate.der');
const asn1 = asn1js.fromBER(certDer.buffer);
console.log(asn1);
```

The code above results in the error `Type [UNIVERSAL 0] is reserved`:

```js
{ offset: -1,
  result:
   Constructed {
     blockLength: 0,
     error: 'Type [UNIVERSAL 0] is reserved',
     warnings: [],
     valueBeforeDecode: ArrayBuffer { byteLength: 0 },
     idBlock:
      LocalIdentificationBlock {
        blockLength: 1,
        error: '',
        warnings: [],
        valueBeforeDecode: ArrayBuffer { byteLength: 0 },
        isHexOnly: false,
        valueHex: ArrayBuffer { byteLength: 0 },
        tagClass: 1,
        tagNumber: 7,
        isConstructed: true },
     lenBlock:
      LocalLengthBlock {
        blockLength: 1,
        error: '',
        warnings: [],
        valueBeforeDecode: ArrayBuffer { byteLength: 0 },
        isIndefiniteForm: false,
        longFormUsed: false,
        length: 117 },
     valueBlock:
      LocalConstructedValueBlock {
        blockLength: 0,
        error: 'Type [UNIVERSAL 0] is reserved',
        warnings: [],
        valueBeforeDecode: ArrayBuffer { byteLength: 0 },
        value: [],
        isIndefiniteForm: false } } }
```

Note that I'm generating the certificate above with:

```bash
openssl req \
    -new \
    -newkey rsa:4096 \
    -days 365 \
    -nodes \
    -x509 \
    -subj "/C=GB/ST=Oxfordshire/L=Oxford/O=ACME/CN=example.com" \
    -keyout /dev/null \
    -outform der \
    -out certificate.der
```

I want to do this so I can use PKI.js to generate a CMS enveloped data, per this example: https://github.com/PeculiarVentures/PKI.js/blob/b165c188537274d9dc108df0a0b69cc13e0795eb/examples/HowToEncryptCMSviaCertificate/es6.js#L231

I'm using Node.js v10 in case that's relevant, but I can also reproduce it with Node.js v6.

Thanks in advance.

Gus.

**Comment by rmhrisk** [comment]
Please provide certificate.der

**Comment by gnarea** [comment]
Hi @rmhrisk! Here you go -- compressed because GitHub didn't let me upload a `.der` file: [certificate.der.zip](https://github.com/PeculiarVentures/ASN1.js/files/2732319/certificate.der.zip)

Thanks!

**Comment by YuryStrozhevsky** [comment]
@gnarea I have decoded the certificate without any errors. You can use [this live example](https://pkijs.org/examples/X509_cert_complex_example.html) for the testing. So, I do suspect your issue is only a "Node-specific" issue, not related directly to ASN1js library. You need to check the buffer your functions transfer to ASN1js.

**Comment by gnarea** [comment]
Thanks @YuryStrozhevsky! Upon further debugging, I found that whilst `certDer.buffer` above was indeed an `ArrayBuffer` as required by `asn1js.fromDER()`, it isn't quite returning what I expected: Amongst other things, `certDer.buffer.bufferLength` reported 8192 bytes even though the original `certDer` only had 1420.

I solved this issue using [buffer-to-arraybuffer](https://github.com/miguelmota/buffer-to-arraybuffer) instead of `certDer.buffer`, although I wasn't expecting to have to use something like that in newer versions of Node:

```js
const asn1js = require('asn1js');
const bufferToArrayBuffer = require('buffer-to-arraybuffer');
const fs = require('fs');

const certDer = fs.readFileSync('certificate.der');
const asn1 = asn1js.fromBER(bufferToArrayBuffer(certDer));
console.log(asn1);
```

Thanks for your help! I'll now close this issue.

**Comment by baslr** [comment]
@gnarea 
I also had this problem. Here the solution without `buffer-to-arraybuffer`.

```js
const asn1js = require('asn1js');
const fs = require('fs');

const certDer = fs.readFileSync('certificate.der');
const asn1 = asn1js.fromBER(
    certDer.buffer.slice(certDer.byteOffset, certDer.byteOffset + certDer.byteLength)
);
console.log(asn1);
```

Background: `Buffer.buffer` is a slice of memory where the data is mapped into https://nodejs.org/dist/latest-v12.x/docs/api/buffer.html#buffer_class_property_buffer_poolsize. `Buffer.buffer.slice(offset, offset+length)` returns the buffer data as an `ArrayBuffer`.

**Comment by microshine** [comment]
@gnarea Don't use `buffer` property from NodeJs buffer

```js
var b = Buffer.from("Hello");
b.buffer.byteLength; // 8192
```

You need to wrap `Buffer` to `Uint8Array` to fix it

```js
new Uint8Array(b).buffer.byteLength; // 5
```

**Comment by gnarea** [comment]
Thanks! I've been using `buffer-to-arraybuffer` anyway, which does `Buffer.buffer.slice(offset, offset+length)` behind the scenes.
