### ISSUE TITLE
can't import asn1js

### ISSUE THREAD

**Issue by yulidai** [PeculiarVentures/ASN1.js#43]
when imported into web project, will get undefined

1、how to install?
`yarn add asn1js`

2、how to import?
`import asn1js from 'asn1js'`, import success

3、what's wrong?
`console.log(asn1js); //get undefined`

**Comment by YuryStrozhevsky** [comment]
@yulidai Here is a quote from [**main README**](https://github.com/PeculiarVentures/ASN1.js#examples):

> More examples could be found in "examples" directory or inside PKIjs library

Here is [**the link to examples folder**](https://github.com/PeculiarVentures/ASN1.js/tree/master/examples/ASN1Usage), here is [**the link to examples folder in PKIjs project**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples).

Here is correct import code:
```javascript
import * as asn1js from "asn1js";
```

**Comment by yulidai** [comment]
Thanks, import success now.

**Comment by yulidai** [comment]
I have another question which related `BER` and `DER`

- What i have got?
i get signature which seems encoded by `DER` from my ledger(hard wallet ), the signature showed below（encode by base64):
```
MEQCID92H7jJQvQ3WL/hOIwRds/eSeMsekLr7CUqZBuioIwhAiABtRhkwx0kp53t+RSFf4bl8rgzgrGQPWDxCyO2/gmUjA==
```

- What i want?
Seems encoded by `BER`
```
P3YfuMlC9DdYv+E4jBF2z95J4yx6QuvsJSpkG6KgjCEBtRhkwx0kp53t+RSFf4bl8rgzgrGQPWDxCyO2/gmUjA==
```

- How to get it now？
For getting this, i remove pre bytes from `DER` and left last 66 bytes, then remove the 33th and 34th bytes, ultimately, 64 bytes are left, then it's what i want.

- What help do you expect?
i wonder if it is possible convert this by using asn1js

- Causes of problems
[https://github.com/ZondaX/ledger-cosmos-js/issues/17](url)

i'm not very familiar with asn1js, very sorry if my question is silly. would be very grateful if can get some help 😃

**Comment by yulidai** [comment]
```
P3YfuMlC9DdYv+E4jBF2z95J4yx6QuvsJSpkG6KgjCEBtRhkwx0kp53t+RSFf4bl8rgzgrGQPWDxCyO2/gmUjA==
```
this signature is the result of signing by secp256k1

**Comment by rmhrisk** [comment]
If you have not answered your question please create a new issue covering your new question.

**Comment by YuryStrozhevsky** [comment]
@yulidai You need firstly decode BASE-64 string data to ArrayBuffer. In the example bellow I am using [**pvutils**](https://github.com/PeculiarVentures/pvutils). And notice that the key has two parts, you referenced to just first part of the key.

```javascript
const asn1 = asn1js.fromBER(pvutils.stringToArrayBuffer(pvutils.fromBase64(yourWonderfulData)));

const firstPartOfKey = asn1.result.valueBlock.value[0].valueBlock.valueHex; // Would be ArrayBuffer having the data you referenced
const secondPartOfKey = asn1.result.valueBlock.value[1].valueBlock.valueHex;
```

**Comment by yulidai** [comment]
@YuryStrozhevsky 
Yes! I get the result by
```
let resultKey = pvutils.utilConcatBuf(firstPartOfKey, secondPartOfKey)
console.log(pvutils.toBase64(pvutils.arrayBufferToString(resultKey)))
```

Thank you very much!!!! 👍 👍 👍

**Comment by yulidai** [comment]
@YuryStrozhevsky 
I test a lot of data, always get the right signature. it's awesome.
But, only this signature seems get wrong:
```javascript
let originCode = 'MEUCIQC/5VGwI2h9v/f85q4rvxg2Wukbme4NNdvAnYr2koO7SgIgIJ6dLT/1Z4fe9AdI17LpnSUJc8q9/U+3t/uGOWdQl2w='
let asn1 = asn1js.fromBER(pvutils.stringToArrayBuffer(pvutils.fromBase64(res.signature.toString('base64'))));
let firstPartOfKey = asn1.result.valueBlock.value[0].valueBlock.valueHex;
let secondPartOfKey = asn1.result.valueBlock.value[1].valueBlock.valueHex;
let resultKey = pvutils.utilConcatBuf(firstPartOfKey, secondPartOfKey);
// expect get 'v+VRsCNofb/3/OauK78YNlrpG5nuDTXbwJ2K9pKDu0ognp0tP/Vnh970B0jXsumdJQlzyr39T7e3+4Y5Z1CXbA=='
// but    get 'AL/lUbAjaH2/9/zmriu/GDZa6RuZ7g0128CdivaSg7tKIJ6dLT/1Z4fe9AdI17LpnSUJc8q9/U+3t/uGOWdQl2w='
console.log(resultKey);
```

That's confusing

**Comment by YuryStrozhevsky** [comment]
@yulidai This is how your signature looks like when decoded:
```asn1
SEQUENCE {
   INTEGER
     00 BF E5 51 B0 23 68 7D BF F7 FC E6 AE 2B BF 18
     36 5A E9 1B 99 EE 0D 35 DB C0 9D 8A F6 92 83 BB
     4A
   INTEGER
     20 9E 9D 2D 3F F5 67 87 DE F4 07 48 D7 B2 E9 9D
     25 09 73 CA BD FD 4F B7 B7 FB 86 39 67 50 97 6C
   }
```
The difference is in the leading zeros. If you will cut the leading zeros (could be in both parts) then you will get the result you expect.

**Comment by yulidai** [comment]
@YuryStrozhevsky 
Yes, i got right result after remove leading zeros.

So is it possible to have fewer bytes than 32 and then i need to fill in 0?

**Comment by YuryStrozhevsky** [comment]
@yulidai No. If you have highest bit in highest byte equal to 1 then you need to append 0. It is from ASN.1 encoding rules.

**Comment by yulidai** [comment]
@YuryStrozhevsky 
Thanks, so adding `.slice(32)` after `valueHex`  will always get the right result, right? 😄 
```
let originCode = 'MEUCIQC/5VGwI2h9v/f85q4rvxg2Wukbme4NNdvAnYr2koO7SgIgIJ6dLT/1Z4fe9AdI17LpnSUJc8q9/U+3t/uGOWdQl2w='
let asn1 = asn1js.fromBER(pvutils.stringToArrayBuffer(pvutils.fromBase64(res.signature.toString('base64'))));
let firstPartOfKey = asn1.result.valueBlock.value[0].valueBlock.valueHex.slice(-32);
let secondPartOfKey = asn1.result.valueBlock.value[1].valueBlock.valueHex.slice(-32);
let resultKey = pvutils.utilConcatBuf(firstPartOfKey, secondPartOfKey);
// expect get 'v+VRsCNofb/3/OauK78YNlrpG5nuDTXbwJ2K9pKDu0ognp0tP/Vnh970B0jXsumdJQlzyr39T7e3+4Y5Z1CXbA=='
// but    get 'AL/lUbAjaH2/9/zmriu/GDZa6RuZ7g0128CdivaSg7tKIJ6dLT/1Z4fe9AdI17LpnSUJc8q9/U+3t/uGOWdQl2w='
console.log(resultKey);
```

**Comment by YuryStrozhevsky** [comment]
@yulidai Well, yes, could works.

**Comment by yulidai** [comment]
@YuryStrozhevsky Great! Thank you for your patience again!  ^_^

**Comment by YuryStrozhevsky** [comment]
@yulidai Seems it is the rare day when I have a lot of patience, lucky you ;)
