### ISSUE TITLE
Add a commonJS build so jest runner doesn't fail when transforming this dependency

### ISSUE THREAD

**Issue by LiamDotPro** [PeculiarVentures/ASN1.js#47]
Hello,

I'm currently using asn1js as a dependency in my React application and I'm using the built in Jest test runner. Whenever I go to to test anything to do with my certificate library I encounter an error as follows:

 ```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as asn1js from "asn1js";
                                                                                                    ^

    SyntaxError: Unexpected token *
```

My understanding is if this dependency was to also serve a commonJS build then I should be able to test my code with this dependency present.

**Comment by YuryStrozhevsky** [comment]
@LiamDotPro The ASN1.js is initially a ES6 library. So, you could build it in any code you like. I do suggest you to check [**.babelrc**](https://github.com/PeculiarVentures/ASN1.js/blob/master/.babelrc) and adjust target you need for build (and then re-build, of course).

**Comment by LiamDotPro** [comment]
Is there any scope to directly serve a commonJS build alongside this dependency so that people with my use case can carry on using this without needing to fork and build/rebuild?

**Comment by YuryStrozhevsky** [comment]
You are free to make your own fork, rebuild as you wish and publish it to those people.

**Comment by rmhrisk** [comment]
We made the decision to move to ES2015 modules when the became ubiquitously supported. I don’t see it worth adding support for CommonJS as it is isn’t needed anymore given there has been native model support in JS  for quite some time. 

Some history:
 https://link.medium.com/KbKGJoOqKY
