### ISSUE TITLE
[IDEA] Support for content specific tag

### ISSUE THREAD

**Issue by Asphiii** [PeculiarVentures/ASN1.js#50]
Hello,
I think it would be fantastic if ASN1.js could encode the "Content-Specific" tag.
https://stackoverflow.com/questions/43054408/what-is-asn-1-der-tag-value-0xa0
Best regards,
Asphiii

**Comment by YuryStrozhevsky** [comment]
**[HINT] Read the README carefully**

There you could find text
```console
More examples could be found in "examples" directory or inside PKIjs library
```
So, there are s lot of "context-specific tags" and such. [**Here**](https://github.com/PeculiarVentures/PKI.js/blob/master/src/SignedData.js#L149) is one of such "schema" functions.
