### ISSUE TITLE
First moments with ASN1.js

### ISSUE THREAD

**Issue by rafalsk** [PeculiarVentures/ASN1.js#53]
We're having trouble with properly importing the library; within HTML file:
` <script type="module"> 
   import * as asn1js from "/ASN1/src/asn1.js";
   </script>`

results in an error:

> Uncaught TypeError: Failed to resolve module specifier "pvutils". Relative references must start with either "/", "./", or "../".

Found that it's some kind of your 'utility' library. Include it within main-branch ? include info where to find?

**Comment by rmhrisk** [comment]
Did you compile the project?

https://github.com/PeculiarVentures/ASN1.js/blob/master/package.json#L56

**Comment by rafalsk** [comment]
May I suggest there to be an introduction/example for people coming from back-end background and willing to use ASN.JS using JavaScript without employing Babel/NODE.JS-utils and other stuff they might not be familiar with?

**Comment by rmhrisk** [comment]
Did you install the dependencies?

Based on your post it seems what your having problem with is Node, the node package manager and ES6, not ASN1.js. 

There are many resources on how to use these things and the best sources for these things will not be this repository.

With that said the first thing I do when I look at a new open-source node project is look at the package.json to see what tools the developer provided for working with the project.

Then I look at the documentation, tests, and examples provided on usage and try to get them to work.

Then I begin looking at how to apply to my specific problem.

With that background, you can see in the package.json:

```
  "scripts": {
    "build": "babel src --compact=false --out-dir build --source-maps",
    "watch": "babel src --compact=false --out-dir build --source-maps --watch",
    "ex1": "cd examples/ASN1Usage && npm run build && cd ../..",
    "build:examples": "npm run ex1",
    "build:tests": "npm run build:examples",
    "test": "cross-env NODE_ENV=test nyc mocha --require @babel/register",
    "prepublishOnly": "npm run build"
  },
```

With this, you can see you can build the package to begin using it and there are examples you can use as well. 

I had not used this machine for development before so and I encountered a dependency issue with `fsevents` on my platform which is something that babel is dependent on, to work around this issue I searched [StackOverflow](https://stackoverflow.com/questions/46872922/broken-c-std-libraries-on-macos-high-sierra-10-13/47401866#47401866) for the error (which again is environmental) and it said to

```
 mv /usr/local/include/ /usr/local/include_old
```

Which I did, and then I ran it again with the same commands and it worked:

```
git clone https://github.com/PeculiarVentures/ASN1.js.git
cd ASN1.js
npm i
npm run build
```

You can also see it is possible to use without transpiling with babel by looking at the tests:

https://github.com/PeculiarVentures/ASN1.js/blob/master/test/testSuite.js#L1

**Comment by YuryStrozhevsky** [comment]
@rafalsk First of all read README:

> More examples could be found in "examples" directory or inside PKIjs library.

Then read [**this**](https://github.com/PeculiarVentures/PKI.js#how-to-use-pkijs-es6-files-directly-in-browser). And check [**this example**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/HowToUseES6DirectlyInBrowser).
