### ISSUE TITLE
Get decoded result just based on the tag (Applications) 

### ISSUE THREAD

**Issue by ashkank83** [PeculiarVentures/ASN1.js#57]
Hi,
Is it possible to get a decoded result just based on the application/tag numbers. I'm wondering if we can convert the decoded BER to look like following:

```
{
          "1": {
              "4" : {
                  "196" : "BBKTD",
                  "182" : "2SP50",
                  "109" : 33353,
                  "108" : {
                      "16" : 20201105005515,
                      "231" : "+0100"
                  }
              }
          }
      }
}
```

**Comment by YuryStrozhevsky** [comment]
```javascript
const asn1 = asn1js.fromBER(arrayBuffer);
const json = JSON.stringify(asn1.result);
```
Then you would also need to apply filters on `stringify`.

**Comment by ashkank83** [comment]
Hi @YuryStrozhevsky ,
Thanks for the quick answer. Is there any examples available please?
Also do we get the values (like string, ...) after fromBER(). I can see the hex value but not the converted one. Thanks

**Comment by YuryStrozhevsky** [comment]
@ashkank83 Check “examples” folder on GitHub.

**Comment by YuryStrozhevsky** [comment]
Also do recommend to read README. There you will also have a link to PKIJS project which is using ASN1JS.
