### ISSUE TITLE
v4.10.1  upgrade v.5.4.1, var is change to const?

### ISSUE THREAD

**Issue by gitHber** [PeculiarVentures/ASN1.js#59]
Is that means you guys don't support es5?

**Comment by YuryStrozhevsky** [comment]
You can build the code using Babel and make ES5 version.

**Comment by gitHber** [comment]
> make ES5 version
Thanks for reply
I know, In my project, it's just a phantom dependencies, most of time we only compile dependencies that we add by ourself

**Comment by gitHber** [comment]
> You can build the code using Babel and make ES5 version.

Thanks for reply
I know, In my project, it's just a phantom dependencies, most of time we only compile dependencies that we add by ourself
