### ISSUE TITLE
New version not pushed or tagged

### ISSUE THREAD

**Issue by wesleytodd** [PeculiarVentures/ASN1.js#66]
Hi! I noticed that the newest version, `2.2.0`, is not pushed or tagged.  Guessing this was just published locally and pushing is not automated.  I would be happy to submit a PR to add `"postpublish": "git push origin && git push origin --tags"` if you like.  In the mean time, would you mind pushing it up?

**Comment by microshine** [comment]
It's my fail. Sorry.

Just pushed tag

**Comment by wesleytodd** [comment]
Thanks, no apologies necessary, it is very common. I only notice because I run a monitor job at work and some packages (like this one) get flagged for security review.  Let me know if you would like the `postpublish` automation.

**Comment by microshine** [comment]
It would be nice. Could you make a PR?
