### ISSUE TITLE
`fromJSON(json)` in `d.ts` is better w/ a return-typedef, or `error TS7010: 'fromJSON', which lacks return-type annotation, implicitly has an 'any' return type`

### ISSUE THREAD

**Issue by xiaohuilam** [PeculiarVentures/ASN1.js#69]
https://github.com/PeculiarVentures/ASN1.js/blob/6cd5d8683ff09d5c9ada30313b62657caf18272c/index.d.ts#L707-L712

```
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✖ Failed to compile.
✔ Browser application bundle generation complete.

Initial Chunk Files | Names   | Raw Size
runtime.js          | runtime | 14.60 kB |

21 unchanged chunks

Build at: 2022-03-20T12:28:14.744Z - Hash: 494411c2fe817cc5 - Time: 6788ms

Error: node_modules/asn1js/index.d.ts:711:18 - error TS7010: 'fromJSON', which lacks return-type annotation, implicitly has an 'any' return type.

711 declare function fromJSON(json: string | object);
                     ~~~~~~~~
```

**Comment by microshine** [comment]
The new version `asn1js@2.3.2` has been published. Please try it

**Comment by xiaohuilam** [comment]
Nicely &amp; Speedy patch! Great thanks!

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Miroshin&nbsp;Stepan ***@***.***&gt;;
发送时间：2022年3月20日(星期天) 晚上8:55
收件人："PeculiarVentures/ASN1.js" ***@***.***&gt;;
抄送："Bruce Lam ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [PeculiarVentures/ASN1.js] `fromJSON(json)` in `d.ts` is better w/ a return-typedef, or `error TS7010: 'fromJSON', which lacks return-type annotation, implicitly has an 'any' return type` (Issue #69)
-----------------------------------

 

 
The new version ***@***.*** has been published. Please try it
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by microshine** [comment]
There is one more way to solve such problems.

### tsconfig.json
```
// Skip type checking all .d.ts files.
"skipLibCheck": true,
```
