### ISSUE TITLE
Decoding ObjectIdentifiers with IMPLICT tags

### ISSUE THREAD

**Issue by Caracasa** [PeculiarVentures/ASN1.js#78]
With an ASN1 definition using IMPLICIT tagging I need a push in the right direction how to decode an ObjectIdentifier. 

```
Definition DEFINITIONS AUTOMATIC TAGS ::=
BEGIN

Seq ::= SEQUENCE {
   oid [1] OBJECT IDENTIFIER,
   ...
}

END
```

How would I construct the sequence object for decoding (of the oid) in that case? I read the example in #45 but do not understand how to adapt it to my usecase. 

To be honest at the moment I manually iterate over the sequence and match ids to use primitive objects with the valueBlocks. For asn1js.ObjectIdentifier I failed to instantiate the object from the raw arraybuffer.

**Comment by Caracasa** [comment]
I have now. A very sleek and easy to use approach to the topic "asn1-schema" after setting up the support for the experimental decorators.
We will make good use of it.

```
@AsnType({type: AsnTypeTypes.Sequence})
export class TrapSequence {

@AsnProp({ type: AsnPropTypes.ObjecIdentifier, context: 1, implicit: true })
  public oid: string;  
}

[...]
}
```

**Comment by microshine** [comment]
@Caracasa If you are declaring an RFC ASN.1 schema, you could make a PR of your schema to the current ASN mono repo and allow NodeJS community to use it.
